# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(default=b'', max_length=10, unique=True)),
                ('name', models.CharField(default=b'', max_length=40)),
                ('email', models.CharField(default=b'', max_length=40)),
                ('phone', models.IntegerField(default=b'', max_length=10)),
                ('em_no', models.IntegerField(blank=True, default=b'', max_length=10)),
                ('adhar', models.CharField(blank=True, default=b'', max_length=30)),
                ('city', models.CharField(default=b'', max_length=100)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'', max_length=100)),
                ('DOB', models.CharField(default=b'', max_length=100)),
                ('language', models.CharField(default=b'', max_length=100)),
                ('image', models.CharField(default=b'', max_length=100)),
                ('pwd', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
