# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180318_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
