# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180323_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=b'', unique=True),
        ),
    ]
