# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calamity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('eid', models.CharField(blank=True, default=b'', max_length=100)),
                ('etype', models.CharField(blank=True, default=b'', max_length=100)),
                ('lat', models.CharField(blank=True, default=b'', max_length=100)),
                ('lon', models.CharField(blank=True, default=b'', max_length=100)),
                ('user_id', models.CharField(blank=True, default=b'', max_length=100)),
                ('status', models.CharField(blank=True, default=b'', max_length=100)),
                ('text', models.TextField(blank=True, default=b'')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
