# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-30 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calamitys', '0003_auto_20180330_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calamity',
            name='user_id',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
