# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calamitys', '0005_calamity_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calamity',
            name='timestamp',
        ),
    ]
