# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-30 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calamitys', '0004_auto_20180330_1351'),
        ('calamitys', '0007_calamity_timestamp'),
    ]

    operations = [
    ]
