# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.AutoField(default=b'', primary_key=True, serialize=False, unique=True)),
                ('uname', models.CharField(default=b'', max_length=40)),
                ('pwd', models.CharField(default=b'', max_length=40)),
                ('utype', models.CharField(choices=[(b'U', b'User'), (b'A', b'Admin'), (b'T', b'Team'), (b'S', b'Superadmin')], default=b'U', max_length=20)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
