# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team_id', models.CharField(default=b'', max_length=10, unique=True)),
                ('name', models.CharField(default=b'', max_length=40)),
                ('dept_name', models.CharField(default=b'', max_length=40)),
                ('phone', models.IntegerField(default=b'')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
