# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.IntegerField(default=b''),
        ),
    ]
