# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dept_id', models.IntegerField(blank=True, default=b'')),
                ('dept_name', models.CharField(max_length=40)),
                ('location', models.CharField(default=False, max_length=40)),
                ('team_id', models.CharField(max_length=40)),
                ('uname', models.CharField(default=False, max_length=40)),
                ('dept_pwd', models.CharField(default=False, max_length=40)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
