# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20180330_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='timestamp',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
