# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='timestamp',
        ),
    ]
