# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='utype',
            field=models.CharField(choices=[(b'U', b'User'), (b'A', b'Admin'), (b'T', b'Team'), (b'S', b'Superadmin')], default=b'User', max_length=20),
        ),
    ]
