# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20180325_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
